name: Patch and Build

on:
  push:
    branches: [ "1.20.2" ]
  workflow_dispatch:

jobs:
  compile_1_20_2_core_jar:
    runs-on: windows-latest
    
    permissions:
       contents: write
       actions: write
       
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
        
      - name: Configure Git User Details
        run: |
          git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

      - name: Apply Patches
        run: ./gradlew applyPatches
   
      - name: Build
        run: ./gradlew createReobfBundlerJar
           
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          name: "1.20.2 build"
          body: |
            Foldenor build
            Version: 1.20.2
          tag_name: "1.20.2_${{github.run_number}}"
          files: build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
