name: Patch and Build

on:
  push:
    branches: [ "ver/1.21.11" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      actions: write
       
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        
      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'

      - name: Cache Paperweight
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches/paperweight
          key: ${{ runner.os }}-paperweight-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-paperweight-

      - name: Configure Git User Details
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"

      - name: Apply Patches
        run: ./gradlew applyAllPatches --no-daemon --parallel

      - name: Build MojmapPaperclip
        run: ./gradlew createMojmapPaperclipJar --no-daemon --parallel
           
      - name: Make release
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "Foldenor 1.21.11 release"
          automatic_release_tag: "latest_1.21.11"
          files: foldenor-server/build/libs/*-paperclip-*-mojmap.jar
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
