name: Update Folia ref

on:
  workflow_dispatch:

jobs:
  upload_folia_ref:
    runs-on: ubuntu-latest
    
    permissions:
       contents: write
       actions: write
       
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup node
        uses: actions/setup-node@v1

      - name: Get latest Folia commit
        run: ./gradlew foliaRefLatest
        
      - name: Upload to GitHub
        uses: LasyIsLazy/github-upload-action@v0.1.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          file-path: gradle.properties
          owner: Edenor-Minecraft
          repo: Foldenor
          commit-message: Update Folia reference
          branch-name: 1.20.4
